/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/
#include <stdint.h>
#define ADC_BASE_ADDRESS 		0x40012000UL
#define ADC_CR1_REG_OFFSET 		0x04
#define ADC_CR1_REG_ADDRESS 	(ADC_BASE_ADDRESS + ADC_CR1_REG_OFFSET)
#define RCC_BASE_ADDRESS 		0x40023800UL
#define RCC_APB2_REG_OFFSET		0x44UL
#define RCC_APB2_REG_ADDRESS 	(RCC_BASE_ADDRESS + RCC_APB2_REG_OFFSET)

int main(void)
{

	uint32_t *APB2Clk = (uint32_t*) RCC_APB2_REG_ADDRESS;
	*APB2Clk |= (1 << 8);


	//Note: if you did not enable the APB2 clock registers for
	//ADC, this configuration will not work. Take a look at SFR
	//Solution: use datasheet to configure the APB2 clock
	uint32_t *pAddCr1Reg = (uint32_t*) ADC_CR1_REG_ADDRESS;
	*pAddCr1Reg |= 1 << 8;
	for (;;);
}
